services:
  qwen2api:
    container_name: qwen2api
    image: rfym21/qwen2api:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      # API 路径，不填则为空(http://localhost:3000)
      # 示例(/api) 则访问 http://localhost:3000/api
      - API_PREFIX=
      # 如果需要修改Docker暴露端口，请修改ports中的参数
      # 示例(8080:3000) 则访问 http://localhost:8080
      - SERVICE_PORT=3000
      # API 密钥 (非必填)
      # 如果需要使用多账户或使用内置账户，请填写
      - API_KEY=sk-123456
      # 账号token：多个账号使用","分隔
      # 示例：ey1...,ey2...,ey3...
      - ACCOUNT_TOKENS=
      # 监听地址(非必填)
      - LISTEN_ADDRESS=
      # 搜索信息展示模式
      # table: 使用折叠块和表格展示
      # text: 使用纯文本
      - SEARCH_INFO_MODE=table
      # 是否输出思考过程
      - OUTPUT_THINK=true
